source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.6.0'

#==================================================
# RAILS CORE
#==================================================
gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'dotenv-rails'

#==================================================
# ASSETS - Back-end
#==================================================
gem 'rails-i18n'
gem 'rails_12factor'
gem 'simple_form'
gem 'active_model_serializers'
gem 'devise'
gem 'kaminari'
gem 'groupdate'
gem 'mini_magick'
gem 'friendly_id'

#==================================================
# ASSETS - Integration & Compressors
#==================================================
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

#==================================================
# ASSETS - Front-end
#==================================================
# gem 'popper_js', '~> 1.12.3'
gem 'bootstrap', '~> 4.1.3'
gem 'font-awesome-sass', '~> 5.2.0'
gem 'turbolinks', '~> 5'
gem 'jquery-rails'

#==================================================
# GEM - Development
#==================================================
group :development do
  gem "letter_opener"
  gem 'bullet'
  gem 'pry-meta'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

